name: deploy

on:
  push:
    branches: [rec]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose pull
          docker compose up -d --build